Update gz-sim version required on CMakeLists.txt
gazebosim/gz-launch pull request #195
Opened 2022-08-24 14:59 UTC by Blast545

FYI: @Crola1702 
Signed-off-by: Crola1702 <j.arroyo@uniandes.edu.co>

Signed-off-by: Crola1702 <j.arroyo@uniandes.edu.co>

# 🦟 Bug fix
This addresses the build regressions happening on gz-launci-win, reference build: 
https://build.osrfoundation.org/job/ign_launch-ci-win/70/

## Summary
This PR just bumps the required version on `gz-sim` as a dependency.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-24 15:00 UTC, mjcarroll approved these changes

2022-08-24 15:42 UTC, Blast545 commented
:man_farmer: We saw this PR build failing: https://build.osrfoundation.org/job/ignition_launch-ci-pr_any-ubuntu_auto-amd64/677/ and realized that some of the CI jobs grab their dependencies from the root worskpace, and as the old version of gz-sim7 was still available it pulled this one instead of the new one set with this pr (gz-sim8).

We wiped out the workspace on the agent that failed, and re-ran that job successfully: https://build.osrfoundation.org/job/ignition_launch-ci-pr_any-ubuntu_auto-amd64/678/

Should we wipe out all the workspaces to be able of testing this PR? x.x

2022-08-24 15:45 UTC, Blast545 commented
Why https://github.com/gazebo-tooling/release-tools/blob/dfb3ef95337121df3c88508f6f9077a83170c0ff/jenkins-scripts/lib/dependencies_archive.sh#L560 is not setting the required gz-sim version here? is this expected?

Also, this bit looks like a bug: https://github.com/gazebo-tooling/release-tools/blob/dfb3ef95337121df3c88508f6f9077a83170c0ff/jenkins-scripts/lib/dependencies_archive.sh#L581

2022-08-26 16:21 UTC, j-rivero commented
> man_farmer We saw this PR build failing: https://build.osrfoundation.org/job/ignition_launch-ci-pr_any-ubuntu_auto-amd64/677/ and realized that some of the CI jobs grab their dependencies from the root worskpace, and as the old version of gz-sim7 was still available it pulled this one instead of the new one set with this pr (gz-sim8).

Umm. This is somehow a bug, probably in the buildfarm itself since we probably don't want to support the use case of having two major versions of gz-sim available and bet for a clever selection. Could you please create an issue for it in release-tools?

> [](https://build.osrfoundation.org/job/ignition_launch-ci-pr_any-ubuntu_auto-amd64/678/)
> 
> Should we wipe out all the workspaces to be able of testing this PR? x.x

I see nothing wrong in wiping the workspaces manually, it is tedious a should be fixed but should not make any bad.

2022-08-26 23:50 UTC, chapulina requested changes
humm bumping a library version is something that needs to be done for a reason and requires lots of changes to the entire stack. Most likely Gazebo-H will use `gz-sim8`, but a lot more than just PR will need to be done, see the checklist here:

https://github.com/gazebo-tooling/release-tools/blob/master/.github/ISSUE_TEMPLATE/bump_libraries.md

And examples here:

https://github.com/gazebo-tooling/release-tools/issues?q=is%3Aissue+bump+in+garden+is%3Aclosed+

The `main` branch here should be working against `gz-sim7`. I didn't look into the linked build to see what's the actual problem here, but it shouldn't be the sim version.

2022-08-29 22:27 UTC, j-rivero commented
See https://github.com/gazebo-tooling/gazebodistro/pull/123 as an alternative.

2022-08-29 23:35 UTC, closed without merging