6 -> main 2022-12-07
gazebosim/gz-launch pull request #206
Opened 2022-12-07 19:24 UTC by iche033

# ➡️ Forward port

Port <FROM_BRANCH> to <TO_BRANCH>

Branch comparison: https://github.com/gazebosim/gz-launch/compare/main...gz-launch6

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2022-12-08 06:40 UTC, ahcorde requested changes
Windows and macOX are failing is this expected, it is something related with `gz-gu8`

2022-12-08 23:46 UTC, iche033 commented
hmm the CI backend is not quite ready yet for `gz-launch7`, working on it..

2022-12-15 23:41 UTC, iche033 commented
> hmm the CI backend is not quite ready yet for `gz-launch7`, working on it..

CI builds fixed in https://github.com/gazebosim/gz-launch/pull/207

2022-12-19 08:26 UTC, ahcorde approved these changes

2022-12-19 08:26 UTC, merged